### ISSUE TITLE
Null Data & Open DataReader Errors

### ISSUE THREAD

**Issue by ross1296** [HellSeagull/Roccus---Item-Adder#1]
I hope I'm not doing something wrong here!

![roccus - item adder_2018-10-22_16-21-45](https://user-images.githubusercontent.com/44373013/47303045-e38d9280-d61a-11e8-8aa5-d0ef468aebde.png)
![roccus - item adder_2018-10-22_16-21-10](https://user-images.githubusercontent.com/44373013/47303056-ea1c0a00-d61a-11e8-8dd7-3adad66862b1.png)
![roccus - item adder_2018-10-22_16-21-22](https://user-images.githubusercontent.com/44373013/47303064-ec7e6400-d61a-11e8-8dbb-0b677ae92373.png)

**Comment by HellSeagull** [comment]
Hello, can you describe exactly what you did from start to end, to error and how many lines you had in your tables. Also your game version

**Comment by ross1296** [comment]
Hi there,

1. Opened item adder
2. Choose armor
3. Click max on all the boxes
4. Filled in empty boxes
5. Preview
6. Hotfix

I have amount of 58 lines in tables. Tried on game versions 7.2 and 7.3 trinitycore server.

Is slot box suppose to be empty? There is nothing in it

**Comment by HellSeagull** [comment]
This item adder was made for 7.3.5 database version. I guess you'd need to check the columns of your tables. There must be a problem of table structure since it calls a null value error thus making the dat areader staying opened at the second click. Send me your item, item_appearance, item_modified_appearance, item_sparse and hotfix_data table structure please

**Comment by ross1296** [comment]
item
![image](https://user-images.githubusercontent.com/44373013/47618855-bdab3680-dacf-11e8-9639-409ff1c2b0eb.png)
item appearance
![image](https://user-images.githubusercontent.com/44373013/47618801-3d84d100-dacf-11e8-9566-93d55dff40eb.png)
item modified
![image](https://user-images.githubusercontent.com/44373013/47618808-4a092980-dacf-11e8-9a52-870bcabeea19.png)
hotfix
![image](https://user-images.githubusercontent.com/44373013/47618825-57261880-dacf-11e8-9952-195c5af71cb3.png)

sparse too big to add. Database made by running TrinityCore's worldserver with the required DB files: https://github.com/TrinityCore/TrinityCore/releases/tag/TDB735.00

Sql version 5.7.23 if it helps.

**Comment by HellSeagull** [comment]
CREATE TABLE `item_sparse` (
  `ID` int(10) unsigned NOT NULL DEFAULT '0',
  `AllowableRace` bigint(20) NOT NULL DEFAULT '0',
  `Display` text,
  `Display1` text,
  `Display2` text,
  `Display3` text,
  `Description` text,
  `Flags1` int(11) NOT NULL DEFAULT '0',
  `Flags2` int(11) NOT NULL DEFAULT '0',
  `Flags3` int(11) NOT NULL DEFAULT '0',
  `Flags4` int(11) NOT NULL DEFAULT '0',
  `PriceRandomValue` float NOT NULL DEFAULT '0',
  `PriceVariance` float NOT NULL DEFAULT '0',
  `VendorStackCount` int(10) unsigned NOT NULL DEFAULT '0',
  `BuyPrice` int(10) unsigned NOT NULL DEFAULT '0',
  `SellPrice` int(10) unsigned NOT NULL DEFAULT '0',
  `RequiredAbility` int(10) unsigned NOT NULL DEFAULT '0',
  `MaxCount` int(11) NOT NULL DEFAULT '0',
  `Stackable` int(11) NOT NULL DEFAULT '0',
  `StatPercentEditor1` int(11) NOT NULL DEFAULT '0',
  `StatPercentEditor2` int(11) NOT NULL DEFAULT '0',
  `StatPercentEditor3` int(11) NOT NULL DEFAULT '0',
  `StatPercentEditor4` int(11) NOT NULL DEFAULT '0',
  `StatPercentEditor5` int(11) NOT NULL DEFAULT '0',
  `StatPercentEditor6` int(11) NOT NULL DEFAULT '0',
  `StatPercentEditor7` int(11) NOT NULL DEFAULT '0',
  `StatPercentEditor8` int(11) NOT NULL DEFAULT '0',
  `StatPercentEditor9` int(11) NOT NULL DEFAULT '0',
  `StatPercentEditor10` int(11) NOT NULL DEFAULT '0',
  `StatPercentageOfSocket1` float NOT NULL DEFAULT '0',
  `StatPercentageOfSocket2` float NOT NULL DEFAULT '0',
  `StatPercentageOfSocket3` float NOT NULL DEFAULT '0',
  `StatPercentageOfSocket4` float NOT NULL DEFAULT '0',
  `StatPercentageOfSocket5` float NOT NULL DEFAULT '0',
  `StatPercentageOfSocket6` float NOT NULL DEFAULT '0',
  `StatPercentageOfSocket7` float NOT NULL DEFAULT '0',
  `StatPercentageOfSocket8` float NOT NULL DEFAULT '0',
  `StatPercentageOfSocket9` float NOT NULL DEFAULT '0',
  `StatPercentageOfSocket10` float NOT NULL DEFAULT '0',
  `ItemRange` float NOT NULL DEFAULT '0',
  `BagFamily` int(10) unsigned NOT NULL DEFAULT '0',
  `QualityModifier` float NOT NULL DEFAULT '0',
  `DurationInInventory` int(10) unsigned NOT NULL DEFAULT '0',
  `DmgVariance` float NOT NULL DEFAULT '0',
  `AllowableClass` smallint(6) NOT NULL DEFAULT '0',
  `ItemLevel` smallint(5) unsigned NOT NULL DEFAULT '0',
  `RequiredSkill` smallint(5) unsigned NOT NULL DEFAULT '0',
  `RequiredSkillRank` smallint(5) unsigned NOT NULL DEFAULT '0',
  `MinFactionID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ItemStatValue1` smallint(6) NOT NULL DEFAULT '0',
  `ItemStatValue2` smallint(6) NOT NULL DEFAULT '0',
  `ItemStatValue3` smallint(6) NOT NULL DEFAULT '0',
  `ItemStatValue4` smallint(6) NOT NULL DEFAULT '0',
  `ItemStatValue5` smallint(6) NOT NULL DEFAULT '0',
  `ItemStatValue6` smallint(6) NOT NULL DEFAULT '0',
  `ItemStatValue7` smallint(6) NOT NULL DEFAULT '0',
  `ItemStatValue8` smallint(6) NOT NULL DEFAULT '0',
  `ItemStatValue9` smallint(6) NOT NULL DEFAULT '0',
  `ItemStatValue10` smallint(6) NOT NULL DEFAULT '0',
  `ScalingStatDistributionID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ItemDelay` smallint(5) unsigned NOT NULL DEFAULT '0',
  `PageID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `StartQuestID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `LockID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `RandomSelect` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ItemRandomSuffixGroupID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ItemSet` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ZoneBound` smallint(5) unsigned NOT NULL DEFAULT '0',
  `InstanceBound` smallint(5) unsigned NOT NULL DEFAULT '0',
  `TotemCategoryID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `SocketMatchEnchantmentId` smallint(5) unsigned NOT NULL DEFAULT '0',
  `GemProperties` smallint(5) unsigned NOT NULL DEFAULT '0',
  `LimitCategory` smallint(5) unsigned NOT NULL DEFAULT '0',
  `RequiredHoliday` smallint(5) unsigned NOT NULL DEFAULT '0',
  `RequiredTransmogHoliday` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ItemNameDescriptionID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `OverallQualityID` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `InventoryType` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RequiredLevel` tinyint(4) NOT NULL DEFAULT '0',
  `RequiredPVPRank` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RequiredPVPMedal` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `MinReputation` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `ContainerSlots` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `StatModifierBonusStat1` tinyint(4) NOT NULL DEFAULT '0',
  `StatModifierBonusStat2` tinyint(4) NOT NULL DEFAULT '0',
  `StatModifierBonusStat3` tinyint(4) NOT NULL DEFAULT '0',
  `StatModifierBonusStat4` tinyint(4) NOT NULL DEFAULT '0',
  `StatModifierBonusStat5` tinyint(4) NOT NULL DEFAULT '0',
  `StatModifierBonusStat6` tinyint(4) NOT NULL DEFAULT '0',
  `StatModifierBonusStat7` tinyint(4) NOT NULL DEFAULT '0',
  `StatModifierBonusStat8` tinyint(4) NOT NULL DEFAULT '0',
  `StatModifierBonusStat9` tinyint(4) NOT NULL DEFAULT '0',
  `StatModifierBonusStat10` tinyint(4) NOT NULL DEFAULT '0',
  `DamageDamageType` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Bonding` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `LanguageID` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `PageMaterialID` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Material` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `SheatheType` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `SocketType1` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `SocketType2` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `SocketType3` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `SpellWeightCategory` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `SpellWeight` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `ArtifactID` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `ExpansionID` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `VerifiedBuild` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
 

+ Using MySQL 5.7.22 On my side hmm... It would be awesome if you could make an mp4 video of you full process from the opening of the app to the error (use ShareX application for that with the shift + print screen shortcut to record in mp4, it will be uploaded on a repositery)

**Comment by HellSeagull** [comment]
Ok I managed to reproduce the error. I'll fix that when I can but for now to fix this null data value you need to have at least 1 line in hotfix_data already.
